version: '3.8'

services:
  sbti-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbti-server
    restart: always
    ports:
      - "9999:3000"
    volumes:
      - ./data:/app/data
